Ra 8
Chay23/react-app pull request #27
Opened 2020-12-23 19:17 UTC by Chay23

2020-12-23 19:19 UTC, BogVin approved these changes

2020-12-24 07:09 UTC, doroshroman approved these changes

2020-12-24 07:11 UTC, vladhoi approved these changes

2020-12-24 07:12 UTC, vladhoi requested changes

2020-12-24 07:12 UTC, vladhoi commented on debug.log
> +[1223/184445.680:ERROR:directory_reader_win.cc(43)] FindFirstFile: ������� �� ������� ����� ��������� ����. (0x3)
please remove log file from pr

2020-12-24 08:57 UTC, vladhoi approved these changes

2020-12-24 09:01 UTC, merged